# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr',
            name='usr_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
