# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160526_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr',
            name='usr_type',
            field=models.CharField(max_length=1),
        ),
    ]
